export const CREATE_VIDEO = 'CREATE A VIDEO';
export const TITLE = 'Title';
export const RECORD_AND_SHARE = 'Record and share a personalized video.';
export const UPLOAD_FROM_COMPUTER = 'Upload from Computer';
export const RECORD_WITH_CAMERA = 'Record With Camera';
export const CLICK_AND_DRAG = "Click or Drag File to Upload Video";
export const SEND_THROUGH_EMAIL = 'Send Through Email';
export const SENDER_ADDRESS = 'Reciever Email';
export const SAVE_VIDEO = "Save Video"