const SAVE_CHATVID_REQUEST: string = "SAVE_CHATVID_REQUEST";
const SAVE_CHATVID_SUCCESS: string = "SAVE_CHATVID_SUCCESS";
const SAVE_CHATVID_FAILURE: string = "SAVE_CHATVID_FAILURE";

const GET_CHATVIDS_REQUEST: string = "GET_CHATVIDS_REQUEST";
const GET_CHATVIDS_SUCCESS: string = "GET_CHATVIDS_SUCCESS";
const GET_CHATVIDS_FAILURE: string = "GET_CHATVIDS_FAILURE";

const GET_CHATVID_REQUEST: string = "GET_CHATVID_REQUEST";
const GET_CHATVID_SUCCESS: string = "GET_CHATVID_SUCCESS";
const GET_CHATVID_FAILURE: string = "GET_CHATVID_FAILURE";

const REPLY_TO_CHATVID_REQUEST: string = "REPLY_TO_CHATVID_REQUEST";
const REPLY_TO_CHATVID_SUCCESS: string = "REPLY_TO_CHATVID_SUCCESS";
const REPLY_TO_CHATVID_FAILURE: string = "REPLY_TO_CHATVID_FAILURE";

const ADD_STEP_TO_CHATVID_REQUEST: string = "ADD_STEP_TO_CHATVID_REQUEST";
const ADD_STEP_TO_CHATVID_SUCCESS: string = "ADD_STEP_TO_CHATVID_SUCCESS";
const ADD_STEP_TO_CHATVID_FAILURE: string = "ADD_STEP_TO_CHATVID_FAILURE";

const SAVE_ANALYTICS_CHATVID_REQUEST: string = "SAVE_ANALYTICS_CHATVID_REQUEST";
const SAVE_ANALYTICS_CHATVID_SUCCESS: string = "SAVE_ANALYTICS_CHATVID_SUCCESS";
const SAVE_ANALYTICS_CHATVID_FAILURE: string = "SAVE_ANALYTICS_CHATVID_FAILURE";

const GET_ANALYTICS_CHATVID_REQUEST: string = "GET_ANALYTICS_CHATVID_REQUEST";
const GET_ANALYTICS_CHATVID_SUCCESS: string = "GET_ANALYTICS_CHATVID_SUCCESS";
const GET_ANALYTICS_CHATVID_FAILURE: string = "GET_ANALYTICS_CHATVID_FAILURE";

const DELETE_CHATVID_REQUEST: string = "DELETE_CHATVID_REQUEST";
const DELETE_CHATVID_SUCCESS: string = "DELETE_CHATVID_SUCCESS";
const DELETE_CHATVID_FAILURE: string = "DELETE_CHATVID_FAILURE";

const SELECT_CHATVID: string = "SELECT_CHATVID";
const UPDATE_CHATVID_JUMP: string = "UPDATE_CHATVID_JUMP";

export const types = {
  SAVE_CHATVID_REQUEST,
  SAVE_CHATVID_SUCCESS,
  SAVE_CHATVID_FAILURE,
  GET_CHATVIDS_REQUEST,
  GET_CHATVIDS_SUCCESS,
  GET_CHATVIDS_FAILURE,

  GET_CHATVID_REQUEST,
  GET_CHATVID_SUCCESS,
  GET_CHATVID_FAILURE,

  REPLY_TO_CHATVID_REQUEST,
  REPLY_TO_CHATVID_SUCCESS,
  REPLY_TO_CHATVID_FAILURE,

  ADD_STEP_TO_CHATVID_REQUEST,
  ADD_STEP_TO_CHATVID_SUCCESS,
  ADD_STEP_TO_CHATVID_FAILURE,

  SAVE_ANALYTICS_CHATVID_REQUEST,
  SAVE_ANALYTICS_CHATVID_SUCCESS,
  SAVE_ANALYTICS_CHATVID_FAILURE,
  
  GET_ANALYTICS_CHATVID_REQUEST,
  GET_ANALYTICS_CHATVID_SUCCESS,
  GET_ANALYTICS_CHATVID_FAILURE,
  
  DELETE_CHATVID_REQUEST,
  DELETE_CHATVID_SUCCESS,
  DELETE_CHATVID_FAILURE,

  SELECT_CHATVID,
  UPDATE_CHATVID_JUMP,
};