const ADD_CONTACT: string = "ADD_CONTACT";
const ADD_CONTACT_SUCCESS: string = "ADD_CONTACT_SUCCESS";
const ADD_CONTACT_FAILURE: string = "ADD_CONTACT_FAILURE";
const UPDATE_CONTACT: string = "UPDATE_CONTACT";
const UPDATE_CONTACT_SUCCESS: string = "UPDATE_CONTACT_SUCCESS";
const UPDATE_CONTACT_FAILURE: string = "UPDATE_CONTACT_FAILURE";

export const types = {
    ADD_CONTACT,
    ADD_CONTACT_SUCCESS,
    ADD_CONTACT_FAILURE,
    UPDATE_CONTACT,
    UPDATE_CONTACT_SUCCESS, UPDATE_CONTACT_FAILURE
}